export default {
    // 查询业态类型
    listFunctionTypesService: "/EMS_SaaS_Web/Spring/MVC/entrance/unifier/listFunctionTypesService",
    // 查询部门-岗位-人员树形结构
    personTree: "/saas/restDeptService/queryDeptPositionPersonTree",
    // 所属部门树形结构
    queryDeptTree: "/saas/restDeptService/queryDeptTree",
    // 搜索物理世界对象
    searchObject: "/saas/restObjectService/searchObject",
    // 搜索物理世界对象类
    searchObjectClass: "/saas/restObjectService/searchObjectClass",
    // 查询通用系统类
    querySystemClass: "/saas/restObjectService/querySystemClass",
    // 查询通用设备
    queryEquipClass: "/saas/restObjectService/queryEquipClass",
    // 查询空间功能类型
    querySpaceClass: "/saas/restObjectService/querySpaceClass",
    // 查询楼层类型
    queryFloorType: "/saas/restObjectService/queryFloorType",
    // 查询竖井性质信息
    queryShaftType: "/saas/restShaftService/queryShaftType",
    // 查询建筑功能类型
    queryBuildFuncType: "/saas/restObjectService/queryBuildFuncType",
    // 查询建筑体
    queryBuild: "/saas/restObjectService/queryBuild",
    // 查询楼层
    queryFloor: "/saas/restObjectService/queryFloor",
    // 查询楼层
    queryShaft: "/saas/restObjectService/queryShaft",
    // 查询空间
    querySpace: "/saas/restObjectService/querySpace",
    // 查询系统实例
    querySystem: "/saas/restObjectService/querySystem",
    // 查询建筑-楼层-空间列表树
    queryBuildFloorSpaceTree: "/saas/restObjectService/queryBuildFloorSpaceTree",
    // 查询设备实例
    queryEquip: "/saas/restObjectService/queryEquip",
    // 查询工单流转的控制模块
    queryGeneralDictByKey: "/saas/restGeneralDictService/queryGeneralDictByKey",
    // 查询工单类型
    queryWoTypeList: "/saas/restGeneralDictService/queryWoTypeList",
    // 根据查询人员详细信息
    queryPersonDetailById: '/saas/restPersonService/queryPersonDetailById',
    // 获取当前人员拥有的项目信息
    queryPersonDetailByPersonId: '/saas/restPersonService/queryPersonDetailByPersonId',
    // 查询专业--系统--设备
    queryDomainSystemEquipType: '/saas/restDictService/queryDomainSystemEquipType',
    // 岗位树
    queryDeptPositionTree: '/saas/restDeptService/queryDeptPositionTree',
    // 岗位树
    queryDeptPositionTreeNew: '/saas/restDeptService/queryDeptPositionTree',
};
